INSERT INTO user (email, password, nickname, profile_image, is_deleted)
VALUES ('user1@test.com', 'password1', 'user1', NULL, false),
       ('user2@test.com', 'password2', 'user2', NULL, false),
       ('user3@test.com', 'password3', 'user3', NULL, false),
       ('user4@test.com', 'password4', 'user4', NULL, false),
       ('user5@test.com', 'password5', 'user5', NULL, false),
       ('user6@test.com', 'password6', 'user6', NULL, false),
       ('user7@test.com', 'password7', 'user7', NULL, false),
       ('user8@test.com', 'password8', 'user8', NULL, false),
       ('user9@test.com', 'password9', 'user9', NULL, false),
       ('user10@test.com', 'password10', 'user10', NULL, false),
       ('user11@test.com', 'password11', 'user11', NULL, false),
       ('user12@test.com', 'password12', 'user12', NULL, false),
       ('user13@test.com', 'password13', 'user13', NULL, false),
       ('user14@test.com', 'password14', 'user14', NULL, false),
       ('user15@test.com', 'password15', 'user15', NULL, false),
       ('user16@test.com', 'password16', 'user16', NULL, false),
       ('user17@test.com', 'password17', 'user17', NULL, false),
       ('user18@test.com', 'password18', 'user18', NULL, false),
       ('user19@test.com', 'password19', 'user19', NULL, false),
       ('user20@test.com', 'password20', 'user20', NULL, false),
       ('user21@test.com', 'password21', 'user21', NULL, false),
       ('user22@test.com', 'password22', 'user22', NULL, false),
       ('user23@test.com', 'password23', 'user23', NULL, false),
       ('user24@test.com', 'password24', 'user24', NULL, false),
       ('user25@test.com', 'password25', 'user25', NULL, false),
       ('user26@test.com', 'password26', 'user26', NULL, false),
       ('user27@test.com', 'password27', 'user27', NULL, false),
       ('user28@test.com', 'password28', 'user28', NULL, false),
       ('user29@test.com', 'password29', 'user29', NULL, false),
       ('user30@test.com', 'password30', 'user30', NULL, false);

INSERT INTO vet_facility (vet_facility_type, province, name, location, lot_address, road_address,
                          phone_number, place_url, grade, bookmark_count, is_deleted)
VALUES ('HOSPITAL', 'SEOUL', '서울동물병원', null, '서울 중구 남대문로 1', '서울 중구 세종대로 110',
        '02-123-4567', null, 0.0, 0, false),
       ('PHARMACY', 'BUSAN', '부산동물약국', null, '부산 중구 중앙대로 1', '부산 중구 중앙로 12',
        '051-234-5678', null, 0.0, 0, false),
       ('HOSPITAL', 'DAEGU', '대구동물병원', null, '대구 중구 동성로 1', '대구 중구 중앙대로 55',
        '053-345-6789', null, 0.0, 0, false),
       ('PHARMACY', 'GANGWONDO', '강원동물약국', null, '강원 원주시 봉산로 1', '강원 원주시 중앙로 22',
        '033-456-7890', null, 0.0, 0, false),
       ('HOSPITAL', 'JEJUDO', '제주동물병원', null, '제주 제주시 중앙로 1', '제주 제주시 신대로 99',
        '064-567-8901', null, 0.0, 0, false),
       ('PHARMACY', 'ULSAN', '울산동물약국', null, '울산 남구 번영로 1', '울산 남구 삼산로 78',
        '052-333-4444', NULL, 0.0, 0, false),
       ('HOSPITAL', 'DAEJEON', '대전동물병원', null, '대전 중구 중앙로 1', '대전 중구 대종로 45',
        '042-111-2222', NULL, 0.0, 0, false);